### ISSUE TITLE
crash when I run jar file 

### ISSUE THREAD

**Issue by Yumore** [ganeshsp1/Flutter_Bluetooth_PC_Control#1]
java environment

java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

java -jar bluetooth_pc_control.jar 
dyld: lazy symbol binding failed: Symbol not found: _IOBluetoothLocalDeviceReadSupportedFeatures
  Referenced from: /private/var/folders/kv/d89x1lgd5mlc72kb2v61hnf00000gn/T/bluecove_nathaniel_0/libbluecove.jnilib
  Expected in: /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth

dyld: Symbol not found: _IOBluetoothLocalDeviceReadSupportedFeatures
  Referenced from: /private/var/folders/kv/d89x1lgd5mlc72kb2v61hnf00000gn/T/bluecove_nathaniel_0/libbluecove.jnilib
  Expected in: /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth

[1]    48706 abort      java -jar bluetooth_pc_control.jar

any solutions

**Comment by ganeshsp1** [comment]
can you try loading the java application in eclipse or any other IDE and running it there

**Comment by Yumore** [comment]
@ganeshsp1 not work, maybe I should change dependencies jar file version, I will rerun later
